
#include "settings.hpp"
void generated_time_eq(std::vector<double>& u,
               std::vector<double>& u1,
               std::vector<double>& v,
               std::vector<double>& v1,
               const uint offset_X,
               const uint offset_Y,
               const uint offset_Z,
               const double h_X,
               const double h_Y,
               const double h_Z,
               const double tau,
               const size_t dimSize);
void generated_impl_eq(std::vector<double>& p,
               std::vector<double>& u,
               std::vector<Eigen::Triplet<double>>& triplets0,
               Eigen::VectorXd& B0,
               const uint offset_X,
               const uint offset_Y,
               const uint offset_Z,
               const double h_X,
               const double h_Y,
               const double h_Z,
               const double tau,
               const size_t dimSize);
